// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408160546_AddRecommendationValueObjects")]
    partial class AddRecommendationValueObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Recommendations.FoodPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<decimal>("AveragePricePerPerson")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("average_price_per_person");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("ExternalMapId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_map_id");

                    b.Property<bool>("IsOpenNow")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open_now");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<double>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.HasKey("Id")
                        .HasName("pk_food_places");

                    b.ToTable("FoodPlaces", "public");
                });

            modelBuilder.Entity("Domain.Recommendations.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CookingTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cooking_time_minutes");

                    b.Property<string>("Cuisine")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cuisine");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("estimated_cost");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingredients");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("steps");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.ToTable("Recipes", "public");
                });

            modelBuilder.Entity("Domain.Recommendations.RecommendationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("pk_recommendation_sessions");

                    b.ToTable("RecommendationSessions", "public");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.PrimitiveCollection<List<string>>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_todo_items");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_todo_items_user_id");

                    b.ToTable("todo_items", "public");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Domain.Recommendations.FoodPlace", b =>
                {
                    b.OwnsOne("Domain.Recommendations.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("FoodPlaceId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Location_City");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Location_Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Location_Longitude");

                            b1.HasKey("FoodPlaceId");

                            b1.ToTable("FoodPlaces", "public");

                            b1.WithOwner()
                                .HasForeignKey("FoodPlaceId")
                                .HasConstraintName("fk_food_places_food_places_id");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Recommendations.RecommendationSession", b =>
                {
                    b.OwnsOne("Domain.Recommendations.BudgetRange", "Budget", b1 =>
                        {
                            b1.Property<Guid>("RecommendationSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Max")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Budget_Max");

                            b1.Property<decimal>("Min")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Budget_Min");

                            b1.HasKey("RecommendationSessionId");

                            b1.ToTable("RecommendationSessions", "public");

                            b1.WithOwner()
                                .HasForeignKey("RecommendationSessionId")
                                .HasConstraintName("fk_recommendation_sessions_recommendation_sessions_id");
                        });

                    b.OwnsOne("Domain.Recommendations.GeoLocation", "UserLocation", b1 =>
                        {
                            b1.Property<Guid>("RecommendationSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("user_location_city");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("user_location_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("user_location_longitude");

                            b1.HasKey("RecommendationSessionId");

                            b1.ToTable("RecommendationSessions", "public");

                            b1.WithOwner()
                                .HasForeignKey("RecommendationSessionId")
                                .HasConstraintName("fk_recommendation_sessions_recommendation_sessions_id");
                        });

                    b.OwnsOne("Domain.Recommendations.UserPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("RecommendationSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("ActionType")
                                .HasColumnType("integer")
                                .HasColumnName("Preferences_ActionType");

                            b1.Property<string>("CuisinePreference")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Preferences_CuisinePreference");

                            b1.Property<int>("DistancePref")
                                .HasColumnType("integer")
                                .HasColumnName("Preferences_DistancePref");

                            b1.Property<bool>("IsFastFoodAllowed")
                                .HasColumnType("boolean")
                                .HasColumnName("Preferences_IsFastFoodAllowed");

                            b1.Property<bool>("OnlyNearby")
                                .HasColumnType("boolean")
                                .HasColumnName("Preferences_OnlyNearby");

                            b1.HasKey("RecommendationSessionId");

                            b1.ToTable("RecommendationSessions", "public");

                            b1.WithOwner()
                                .HasForeignKey("RecommendationSessionId")
                                .HasConstraintName("fk_recommendation_sessions_recommendation_sessions_id");
                        });

                    b.Navigation("Budget")
                        .IsRequired();

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("UserLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_items_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
